import Link from 'next/link';
import { db } from '@/lib/supabase';
import { addDinner, addGame, addPlayer, createGroup, removePlayer, setDinnerCost, signOut, voteDinner } from './actions';
const money=(n:number)=>(n/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const date=(d:string)=>new Date(d).toLocaleString('pt-BR',{dateStyle:'medium',timeStyle:'short',timeZone:'America/Sao_Paulo'});
export default async function Home(){
 if(!process.env.NEXT_PUBLIC_SUPABASE_URL||!process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY)return <main className="setup"><h1>FutPeladaBr</h1><p>Conecte o projeto Supabase para iniciar. As instruções estão no README.</p></main>;
 const client=await db();const {data:{user}}=await client.auth.getUser();
 if(!user)return <main className="setup"><div className="badge">FutPeladaBr</div><h1>Seu futebol, organizado.</h1><p>Jogadores, escalações, jogos e churrasco em um só lugar.</p><Link className="button" href="/login">Entrar ou criar conta</Link></main>;
 const {data:groups,error}=await client.from('groups').select('id,name,owner_id').order('created_at');
 if(error)return <main className="setup"><h1>Não foi possível carregar seus grupos</h1><p>{error.message}</p></main>;
 const group=groups?.[0];const admin=group?.owner_id===user.id;
 const [pr,gr,dr]=group?await Promise.all([client.from('players').select('*').eq('group_id',group.id).order('name'),client.from('games').select('*').eq('group_id',group.id).order('starts_at',{ascending:false}).limit(12),client.from('dinners').select('*,dinner_votes(user_id,attending)').eq('group_id',group.id).order('event_at',{ascending:false}).limit(8)]):[{data:[]},{data:[]},{data:[]}];
 const players=pr.data??[],games=gr.data??[],dinners=dr.data??[];
 return <main className="shell"><header className="top"><div className="brand"><span className="ball">⚽</span><strong>FutPelada<span>Br</span></strong></div><div className="account"><span>{user.email}</span><form action={signOut}><button className="ghost">Sair</button></form></div></header>
 {!group?<section className="empty"><p className="eyebrow">PRIMEIRO PASSO</p><h1>Crie sua turma</h1><p>Dê um nome ao grupo para começar a organizar as partidas.</p><form action={createGroup} className="inline"><input name="name" required minLength={2} maxLength={80} placeholder="Ex.: Futebol de quinta" aria-label="Nome da turma"/><button>Criar grupo</button></form></section>:<><div className="heading"><div><p className="eyebrow">PAINEL DA TURMA</p><h1>{group.name}</h1><p>{admin?'Você administra este grupo':'Acesso de visitante'}</p></div><div className="stats"><div><b>{players.length}</b><span>jogadores</span></div><div><b>{games.length}</b><span>jogos</span></div></div></div>
 <div className="grid"><section className="card wide"><p className="eyebrow">ELENCO</p><h2>Jogadores</h2>{players.length?<div>{players.map(p=><div className="rosterrow" key={p.id}><div className="avatar">{p.name.slice(0,1).toUpperCase()}</div><div className="grow"><strong>{p.name}</strong><small>{p.positions.join(' · ')}</small></div><div className="rating">{p.skill}/5 <small>técnica</small></div>{admin&&<form action={removePlayer}><input type="hidden" name="group_id" value={group.id}/><input type="hidden" name="id" value={p.id}/><button className="textdanger" aria-label={`Excluir ${p.name}`}>Excluir</button></form>}</div>)}</div>:<p className="muted">Nenhum jogador cadastrado.</p>}
 {admin&&<details><summary>Adicionar jogador</summary><form action={addPlayer} className="formgrid"><input type="hidden" name="group_id" value={group.id}/><label>Nome<input name="name" required minLength={2} maxLength={80}/></label><fieldset><legend>Posições</legend>{['Goleiro','Zagueiro','Lateral','Meio-campo','Atacante'].map(p=><label className="check" key={p}><input type="checkbox" name="positions" value={p}/>{p}</label>)}</fieldset>{[['skill','Habilidade'],['speed','Velocidade'],['vision','Visão de jogo'],['passing','Passe']].map(([key,label])=><label key={key}>{label}<select name={key} defaultValue="3">{[1,2,3,4,5].map(n=><option key={n} value={n}>{n}</option>)}</select></label>)}<button>Salvar jogador</button></form></details>}</section>
 <section className="card"><p className="eyebrow">AGENDA</p><h2>Jogos</h2>{games.map(g=><Link href={`/game/${g.id}`} className="event" key={g.id}><strong>{date(g.starts_at)}</strong><span>{g.venue} →</span></Link>)}{!games.length&&<p className="muted">Ainda não há jogos marcados.</p>}{admin&&<details><summary>Marcar jogo</summary><form action={addGame} className="stack"><input type="hidden" name="group_id" value={group.id}/><label>Data e hora<input name="starts_at" type="datetime-local" required/></label><label>Local<input name="venue" required minLength={2} maxLength={160}/></label><button>Salvar jogo</button></form></details>}</section>
 <section className="card wide"><p className="eyebrow">CONFRATERNIZAÇÃO</p><h2>Churrasco e janta</h2>{dinners.map(d=>{const yes=d.dinner_votes?.filter((v:{attending:boolean})=>v.attending).length??0;return <div className="dinner" key={d.id}><div className="grow"><strong>{d.title}</strong><small>{date(d.event_at)} · {yes} confirmado(s)</small><small>Custo: {money(d.total_cents)} · Por pessoa: {yes?money(Math.ceil(d.total_cents/yes)):'aguardando confirmações'}</small></div><form action={voteDinner} className="vote"><input type="hidden" name="dinner_id" value={d.id}/><button name="attending" value="true" className="secondary">Vou</button><button name="attending" value="false" className="ghost">Não vou</button></form>{admin&&<form action={setDinnerCost} className="cost"><input type="hidden" name="group_id" value={group.id}/><input type="hidden" name="dinner_id" value={d.id}/><input name="amount" type="number" step="0.01" min="0" aria-label="Valor total em reais" placeholder="Valor R$" required/><button>Atualizar</button></form>}</div>})}{!dinners.length&&<p className="muted">Nenhum evento cadastrado.</p>}{admin&&<details><summary>Criar confraternização</summary><form action={addDinner} className="formgrid"><input type="hidden" name="group_id" value={group.id}/><label>Nome<input name="title" required/></label><label>Data e hora<input name="event_at" type="datetime-local" required/></label><button>Criar evento</button></form></details>}</section></div></>}
 </main>;
}
