import Link from 'next/link';
import Image from 'next/image';
import AppShell from './app-shell';
import { groupData, gameDate, upcomingGames, playerStats } from '@/lib/group-data';
import { addDinner, createGroup, setDinnerCost, voteDinner } from './actions';
import ThemeToggle from './theme-toggle';
import { ArrowUpRight, CalendarDays, Shirt, Trophy, Users } from 'lucide-react';

const money = (n:number) => (n/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});

export default async function Home({searchParams}:{searchParams:Promise<{group?:string}>}) {
  if (!process.env.NEXT_PUBLIC_SUPABASE_URL || !process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY) return <main className="setup"><h1>FutPeladaBr</h1><p>Conecte o projeto Supabase para iniciar.</p></main>;
  const {user,groups,group,players,games,appearances,client} = await groupData((await searchParams).group);
  if (!user) return <main className="setup login-card"><div className="login-theme"><ThemeToggle compact/></div><Image className="hero-logo" src="/futpeladabr-logo.png" alt="FutPeladaBr — gestão da pelada semanal" width={1698} height={926} priority/><h1>Seu futebol, organizado.</h1><p>Jogadores, escalações, jogos e churrasco em um só lugar.</p><Link className="button" href="/login">Entrar ou criar conta</Link></main>;
  const ranking = playerStats(players,appearances);
  const activePlayers=players.filter(p=>p.active);
  const averageRating=activePlayers.length ? (activePlayers.reduce((sum,p)=>sum+(p.skill+p.speed+p.vision+p.passing)/4,0)/activePlayers.length).toFixed(1).replace('.',',') : '—';
  const artilheiro = ranking[0]?.goals ? ranking[0] : null;
  const upcoming = upcomingGames(games);
  const nextGame = upcoming[0];
  const {data:dinners,error} = group ? await client.from('dinners').select('*,dinner_votes(user_id,attending)').eq('group_id',group.id).order('event_at',{ascending:false}).limit(8) : {data:[],error:null};
  if (error) throw new Error(error.message);
  const admin = group?.owner_id === user.id;
  return <AppShell groups={groups} group={group} active="dashboard" email={user.email}>
    {!group ? <section className="empty"><p className="eyebrow">PRIMEIRO PASSO</p><h1>Crie sua turma</h1><p>Dê um nome ao grupo para começar a organizar as partidas.</p><form action={createGroup} className="inline"><input name="name" required minLength={2} maxLength={80} placeholder="Ex.: Futebol de quinta" aria-label="Nome da turma"/><button>Criar grupo</button></form></section> : <>
      <section className="dashboard-hero"><div className="hero-copy"><span className="hero-kicker">⚽ A CASA DA SUA PELADA</span><h1>{group.name}</h1><p>{admin?'Organize sua turma e acompanhe cada conquista.':'Acompanhe os jogos e a evolução da turma.'}</p><Link href={`/jogos?group=${group.id}`} className="hero-action">Ver jogos <ArrowUpRight size={17} aria-hidden="true"/></Link></div><div className="hero-next"><div className="pitch-circle" aria-hidden="true"/><span>PRÓXIMA PARTIDA</span><strong>{nextGame?gameDate(nextGame.starts_at):'A definir'}</strong><small>{nextGame?.venue??'Marque o próximo encontro da turma'}</small></div></section>
      <div className="section-heading"><div><p className="eyebrow">VISÃO GERAL</p><h2>O jogo em números</h2></div><span>Temporada da turma</span></div>
      <div className="dashboard-metrics"><Link href={`/jogadores?group=${group.id}`} className="metric"><span>Jogadores</span><strong>{activePlayers.length}</strong><small>{players.length} no elenco</small><Users className="metric-icon" size={22} aria-hidden="true"/></Link><Link href={`/jogos?group=${group.id}`} className="metric"><span>Jogos</span><strong>{games.length}</strong><CalendarDays className="metric-icon" size={22} aria-hidden="true"/><small>{upcoming.length} agendado(s)</small></Link><Link href={`/estatisticas?group=${group.id}`} className="metric"><span>Média técnica</span><strong>{averageRating}</strong><small>Notas dos jogadores ativos (1–5)</small><Users className="metric-icon" size={22} aria-hidden="true"/></Link><Link href={`/estatisticas?group=${group.id}`} className="metric highlight"><span>Artilheiro</span><strong>{artilheiro?.name ?? 'A definir'}</strong><small>{artilheiro ? `${artilheiro.goals} gol(s)` : 'Nenhum gol registrado'}</small><Trophy className="metric-icon" size={22} aria-hidden="true"/></Link><Link href={`/jalecos?group=${group.id}`} className="metric"><span>Jalecos</span><strong>Revezamento</strong><small>Confira quem ainda precisa lavar</small><Shirt className="metric-icon" size={22} aria-hidden="true"/></Link></div>
      <div className="grid"><section className="card"><p className="eyebrow">AGENDA</p><h2>Próximos jogos</h2>{upcoming.slice(0,5).map(g=><Link href={`/game/${g.id}`} className="event" key={g.id}><strong>{gameDate(g.starts_at)}</strong><span>{g.venue} →</span></Link>)}{!upcoming.length&&<p className="muted">Ainda não há jogos agendados.</p>}<Link className="section-link" href={`/jogos?group=${group.id}`}>Ver todos os jogos →</Link></section>
      <section className="card"><p className="eyebrow">ARTILHARIA</p><h2>Gols da turma</h2>{ranking.filter(p=>p.goals>0).slice(0,5).map((p,i)=><div className="stat-row" key={p.id}><span>{i+1}. {p.name}</span><strong>{p.goals}</strong></div>)}{!artilheiro&&<p className="muted">Registre gols nas partidas para formar o ranking.</p>}<Link className="section-link" href={`/estatisticas?group=${group.id}`}>Ver estatísticas e comparar →</Link></section>
      <section className="card full"><p className="eyebrow">CONFRATERNIZAÇÃO</p><h2>Churrasco e janta</h2>{(dinners??[]).map(d=>{const yes=d.dinner_votes?.filter((v:{attending:boolean})=>v.attending).length??0;return <div className="dinner" key={d.id}><div className="grow"><strong>{d.title}</strong><small>{gameDate(d.event_at)} · {yes} confirmado(s)</small><small>Custo: {money(d.total_cents)} · Por pessoa: {yes?money(Math.ceil(d.total_cents/yes)):'aguardando confirmações'}</small></div><form action={voteDinner} className="vote"><input type="hidden" name="dinner_id" value={d.id}/><button name="attending" value="true" className="secondary">Vou</button><button name="attending" value="false" className="ghost">Não vou</button></form>{admin&&<form action={setDinnerCost} className="cost"><input type="hidden" name="group_id" value={group.id}/><input type="hidden" name="dinner_id" value={d.id}/><input name="amount" type="number" step="0.01" min="0" aria-label="Valor total em reais" placeholder="Valor R$" required/><button>Atualizar</button></form>}</div>})}{!dinners?.length&&<p className="muted">Nenhum evento cadastrado.</p>}{admin&&<details><summary>Criar confraternização</summary><form action={addDinner} className="formgrid"><input type="hidden" name="group_id" value={group.id}/><label>Nome<input name="title" required/></label><label>Data e hora<input name="event_at" type="datetime-local" required/></label><button>Criar evento</button></form></details>}</section></div>
      <details className="new-group"><summary>Criar outra turma</summary><form action={createGroup} className="inline"><input name="name" required minLength={2} maxLength={80} placeholder="Nome da turma" aria-label="Nome da nova turma"/><button>Criar turma</button></form></details>
    </>}
  </AppShell>;
}
